config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  post '/photos', to: 'static_pages#index'
  get '/photos', to: 'static_pages#index'

  get '/about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		@flickr_id = params[:flickr_id]
	end

	def about
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
# app/helpers/flickr_helper.rb

module FlickrHelper  
  def user_photos(user_id, photo_count = 12)
    FlickRaw.api_key = Figaro.env.api_key
    FlickRaw.shared_secret = Figaro.env.shared_secret

    flickr.photos.search(:user_id => user_id).to_a.values_at(0..photo_count-1)
  end
  
  def render_flickr_sidebar_widget(user_id, photo_count = 12, columns = 2)
    begin
      photos = user_photos(user_id, photo_count).in_groups_of(4)
      render :partial => '/flickr/sidebar_widget', :locals => { :photos => photos }
    rescue Exception
      render :partial => '/flickr/unavailable'
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flickr/_sidebar_widget.html.erb
<div class="flickr">
	<% photos.each do |row| %>
		<div class="row">	
			<% row.each do |p| %>

				<%if p.present?%>
					<div class="col-md-3">
						<div class="thumbnail">
							<%=link_to(image_tag(FlickRaw.url_q(p), :class => 'flickr_photo', :title=> p.title, :border => 0, :size => '200x200'), FlickRaw.url_photopage(p)) %>
						</div>
					</div>
				<%end%>
			<%end%>
		</div>
	<%end%>
</div>

app/views/flickr/_unavailable.html.erb
<p style="text-align: center; padding-top: 1%;">Uh oh..this flickr id doesn't seem to exist.<p>

app/views/layouts/_header.html.erb
  	<nav class="navbar navbar-inverse">
  		<div class="container-fluid">
  			<div class="navbar-header">
  				<a id="h" class="navbar-brand" href=<%=root_path%>>FlickrPics</a>
  			</div>

  			<ul class="nav navbar-nav navbar-right">
     			 <li><a id="h" title="About" href=<%=about_path%>><span class="glyphicon glyphicon-info-sign"></span></a></li>
    		</ul>
  		</div>
  	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrPics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>

  	<div class="container">
   	 <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="row">
	<div  class="col-sm-offset-2 col-sm-8"">
	<h2>About</h2>
<p style="font-size: 18px;">Wanna view your flickr photostream without having to login your credentials?
All you need is your flickr ID, which can be obtained at <a href="https://www.webpagefx.com/tools/idgettr/">idGettr</a>. 
FlickrPics gives you a glimpse of yours or someone else's flickr photos, provided you at least know their flickr username. Have some fun and enter random letters, numbers, and you might get some interesting results. 
For more information, visit the <a href="https://github.com/tfb34/flickr-feed">github</a> page.</p>
	</div>
</div>

app/views/static_pages/index.html.erb
<form action= <%=photos_path%>>

		<div class="input-group">
			
			<input type="text" class="form-control" id="flickr_id" placeholder="Flickr ID" name="flickr_id" >

			<div class="input-group-btn">
				<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-arrow-right"></span>
		    </button>
			</div>
		</div>
</form>

<% if @flickr_id.present? %>
	<div class="widget">
	<%=render_flickr_sidebar_widget(@flickr_id)%>
	</div>
<%else%>
	<p style="text-align: center; padding-top: 1%;">Enter a flickr id. For example, "153186233@N04"</p>
<%end%>